### ISSUE TITLE
problem: problem detail page does not show who resolved it

### ISSUE THREAD

**Issue by gazhayes** [EmurgoHK/Emurgis#100]
problem: when a problem is complete, the problem detail page does not show who resolved the problem once the owner has closed it.

**Comment by samuelralak** [comment]
@emurgobot claim

**Comment by samuelralak** [comment]
@emurgobot label "in progress"

**Comment by samuelralak** [comment]
@emurgobot remove "in progress"
@emurgobot label "done"

**Comment by samuelralak** [comment]
done in #114
