### ISSUE TITLE
problem: [/stats] no statistic for problems that users have completed

### ISSUE THREAD

**Issue by gazhayes** [EmurgoHK/Emurgis#105]
Problem: there's no statisics for problems that a user has claimed and actually solved. The only related statistic is how many of this users logged issues have been solved (regardless of who solved them).

**Comment by AshHimself** [comment]
@emurgobot claim

**Comment by anbud** [comment]
The last one on the table was supposed to be just that, but I just see that I've put the wrong userId in `updateStatus` method. It should be `problem.claimedBy` instead of `Meteor.userId()`.

**Comment by samuelralak** [comment]
#114 adds the following fields to a problem
- resolved (Boolean)
- resolvedBy (userId)
- resolvedDateTime (timestamp)

The above are added when a problem is closed and previous status is `ready for review`. Perhaps this info might come in handy here.

**Comment by AshHimself** [comment]
Fixed in #119
@emurgobot label "done"
@emurgobot done
