### ISSUE TITLE
Problem: no auth system

### ISSUE THREAD

**Issue by gazhayes** [EmurgoHK/Emurgis#11]
Problem: users should be authenticated before being allowed to log issues etc. All users must have a @emurgo.io email account to sign up.

**Comment by samuelralak** [comment]
Will email verification be required for emurg.io accounts?

**Comment by gazhayes** [comment]
Yeah it will. We could use sparkpost or whatever

**Comment by samuelralak** [comment]
@gazhayes should the root route (where all problems are displayed) be protected as well?

**Comment by samuelralak** [comment]
done in [#17](https://github.com/EmurgoHK/Emurgis/pull/17)

**Comment by samuelralak** [comment]
once merged, will create seperate issues for the following
- emurgo.io email verification
- proper validation error message for non @emurgo.io emails (currently showing internal server when user tries to signup with a non @emurgo.io email)

**Comment by gazhayes** [comment]
@samuelralak it just occurred to me that emurgo uses Google apps to handle their email so we can probably use mdg:accounts-google. I'm just not sure if it's possible to restrict it to *@emurgo.io Google accounts though.

**Comment by samuelralak** [comment]
@gazhayes in that case we could use `accounts-google` instead of an email/password login set up. that way it would be easier to verify an `@emurgo.io` account without sending verification emails/codes.

**Comment by gazhayes** [comment]
Ah yeah ok, that's better.

This introduces one small issue however that also has to be addressed (but can be logged as a new issue after):  developers who don't have an emurgo.io account will still need a way to log in.
