### ISSUE TITLE
problem: maintainers cannot delete other users problems

### ISSUE THREAD

**Issue by gazhayes** [EmurgoHK/Emurgis#117]
problem: for housekeeping, it's necessary for some users (maintainers) to be able to delete (hard delete) problems.

solution: create a 'moderator' class of users and allow them to delete other user's problems.

**Comment by anbud** [comment]
@emurgobot claim

How will we choose moderators/maintainers?

**Comment by gazhayes** [comment]
> How will we choose moderators/maintainers?

This can be done manually in DrMongo for now, just tell me where to put the flag ;)

**Comment by anbud** [comment]
Add a `moderator` boolean field set to true in the root of the user object and you'll be able to delete all problems.

Done in #157.

@emurgobot label "done"
