### ISSUE TITLE
problem: cannot filter problems on home route

### ISSUE THREAD

**Issue by gazhayes** [EmurgoHK/Emurgis#118]
Problem: users cannot filter problems by problem status

solution: use checkboxes to filter problems by status. For example "show closed".

**Comment by AshHimself** [comment]
@emurgobot claim

**Comment by AshHimself** [comment]
@gazhayes - do you want the filter to be remembered on page refresh by using cookies or something?

**Comment by AshHimself** [comment]
Fixed in #124 
@emurgobot label "done"
@emurgobot done

I can do another PR if the above is a requirement

**Comment by gazhayes** [comment]
> do you want the filter to be remembered on page refresh by using cookies or something?

Yeah definitely
