### ISSUE TITLE
Problem: button layout on problem detail page is hard to use

### ISSUE THREAD

**Issue by gazhayes** [EmurgoHK/Emurgis#121]
Problem: button layout on problem detail page is hard to use

solution: create a "take action" box at the bottom of the view below the new comment box. Place the "claim" "watch" and "close" etc buttons in there. Move the other buttons to the bottom of the problem detail box instead of at the top.

**Comment by chamidu-supeshala** [comment]
@emurgobot claim

**Comment by chamidu-supeshala** [comment]
fixed #155

@emurgobot done
@emurgobot label "done"
