### ISSUE TITLE
problem: users can close problems that aren't resolved

### ISSUE THREAD

**Issue by gazhayes** [EmurgoHK/Emurgis#122]
problem: users can close problems that aren't resolved.

solution: change button text to "{{username}} has solved this issue" and only display it after an issue has been tagged as "ready for review".

**Comment by samuelralak** [comment]
@emurgobot claim

**Comment by samuelralak** [comment]
@emurgobot unclaim

**Comment by anbud** [comment]
@emurgobot claim

**Comment by anbud** [comment]
Done in #160.

@emurgobot label "done"
