### ISSUE TITLE
problem: wording for "closed" is innacurate

### ISSUE THREAD

**Issue by gazhayes** [EmurgoHK/Emurgis#126]
problem: wording for "closed" is inaccurate

solution: what we're really trying to say is "this is fixed/solved" so it change all "closed" tags, filter checkboxes, etc site wide to "solved".

**Comment by AshHimself** [comment]
@emurgobot claim - i'll take this as well being I am renaming the resolved one at the same time.

@gazhayes - Do I still need two PR requests? or just a single commit referencing both tickets?

**Comment by gazhayes** [comment]
You can always do a single PR for multiple issues, but technically speaking it should be a different *commit* for each problem.

**Comment by AshHimself** [comment]
Fixed in #126
@emurgobot label "done"
@emurgobot done

**Comment by sjmackenzie** [comment]
See #145

**Comment by gazhayes** [comment]
> The name "closed" is generic enough to capture the state of legit problems already solved and non-problems that should be closed immediately.

For open source software development yes, but in this situation it doesn't work (I go into more detail in #145).
