### ISSUE TITLE
problem: "resolved" checkbox is obsolete

### ISSUE THREAD

**Issue by gazhayes** [EmurgoHK/Emurgis#127]
problem: "resolved" checkbox is obsolete (I think). @AshHimself what's this actually for?

**Comment by AshHimself** [comment]
lol I actually don't know. I think I just merged another project I am working on into this one.. i'll remove it.

**Comment by AshHimself** [comment]
@emurgobot claim

**Comment by AshHimself** [comment]
Fixed in #165
@emurgobot label "done"
@emurgobot done
