### ISSUE TITLE
problem: line breaks created by return key do not show on text

### ISSUE THREAD

**Issue by ryankingtm** [EmurgoHK/Emurgis#132]
Solution: Implementation of Markdown? (maybe)

**Comment by AshHimself** [comment]
@emurgobot claim

**Comment by AshHimself** [comment]
Fixed in #140
@emurgobot label "done"
@emurgobot done

**Comment by gazhayes** [comment]
@AshHimself this doesn't seem to be solved, is it parsing MD before or after insert?

**Comment by AshHimself** [comment]
Maybe I didn't understand the issue correctly then.. I am allowing users to pass in markdown and then parsing MD after. Now that I am typing this I think I only did this on comments on not problems text as well.

**Comment by gazhayes** [comment]
> I am allowing users to pass in markdown and then parsing MD after.

That's fine

> I think I only did this on comments on not problems text

That's probably the real problem then. Problem and solution field.

**Comment by AshHimself** [comment]
@emurgobot claim

**Comment by AshHimself** [comment]
@Fixed in #164
@emurgobot label "done"
@emurgobot done

This should be done now. Forgot you can do this in full css so we don't really need the markdown package but can leave it in if you guys want to still do markdown :)

**Comment by gazhayes** [comment]
@ryankingtm when a problem you log is solved (and you have verified that it's solved) you can close it.
