### ISSUE TITLE
problem: number of comments not shown on home route

### ISSUE THREAD

**Issue by gazhayes** [EmurgoHK/Emurgis#134]
problem: the number of comments on each problem are not shown on home route. 

solution: ideally, we would have the number of *new* comments for the currently logged in user (since their last visit to that problem). But if this is too hard the total number of comments is ok.

**Comment by AshHimself** [comment]
@emurgobot claim

**Comment by AshHimself** [comment]
Fixed in #143
@emurgobot label "done"
@emurgobot done
