### ISSUE TITLE
problem: browser dialogues in use

### ISSUE THREAD

**Issue by gazhayes** [EmurgoHK/Emurgis#138]
Problem: browser dialogues look like crap but we are using them for confirmations all over the place.

Solution: change all browser dialogues to modals (or something, there are nicer ways but I can't remember the name right now)

**Comment by AshHimself** [comment]
I am a big fan of https://github.com/t4t5/sweetalert

**Comment by gazhayes** [comment]
Yes that's the one I was thinking of.

**Comment by AshHimself** [comment]
@emurgobot claim

**Comment by AshHimself** [comment]
Fixed in #142 
@emurgobot label "done"
@emurgobot done
