### ISSUE TITLE
problem: cannot log issues for Emurgis itself

### ISSUE THREAD

**Issue by gazhayes** [EmurgoHK/Emurgis#139]
problem: users of Emurgis can't easily log "meta" issues about Emurgis itself. I don't want them to log straight to Github and annoy developers with silly poorly thought out stuff so it's better they log them to Emurgis itself and I'll act as a filter to repost them to github where necessary. 

Solution: add a "This is a problem with Emurgis itself" checkbox to the top of the problem page. Change the background colour of the page/heading/something to indicate this is a different type of category. Add an "Emurgis" tag to the problem and add this to the filter checkboxes.

**Comment by samuelralak** [comment]
@emurgobot claim

**Comment by samuelralak** [comment]
@emurgobot label "in progress"

**Comment by samuelralak** [comment]
@emurgobot remove "in progress"

**Comment by samuelralak** [comment]
@emurgobot label "done"

**Comment by samuelralak** [comment]
done in #197
