### ISSUE TITLE
problem: text in comments overflows box

### ISSUE THREAD

**Issue by gazhayes** [EmurgoHK/Emurgis#167]
problem: text in comments overflows box

<img width="629" alt="screen shot 2018-06-05 at 5 05 53 pm" src="https://user-images.githubusercontent.com/8143945/40966329-ce17a062-68e2-11e8-9a93-5846b954a720.png">

**Comment by AshHimself** [comment]
@emurgobot claim

**Comment by AshHimself** [comment]
Fixed in #170
@emurgobot label "done"
@emurgobot done
