### ISSUE TITLE
problem: strange layout on problem detail page

### ISSUE THREAD

**Issue by gazhayes** [EmurgoHK/Emurgis#171]
problem: strange layout on problem detail page. There's a large amount of space. Not sure if this is UI or MD related.

<img width="537" alt="screen shot 2018-06-05 at 5 35 10 pm" src="https://user-images.githubusercontent.com/8143945/40967949-faeccef6-68e6-11e8-8195-9905c37e3e6d.png">

**Comment by AshHimself** [comment]
That is weird...  want to paste me the markdown in an email or here? or inspect the DOM and see what you see. I think I said in a previous post we can remove markdown if needed but it does add value in a sense so may be worth looking into a tiny bit.

**Comment by gazhayes** [comment]
You can't reproduce locally?
