### ISSUE TITLE
problem: [/stats] wrong abandoned and claimed numbers

### ISSUE THREAD

**Issue by gazhayes** [EmurgoHK/Emurgis#176]
problem: [/stats] wrong abandoned and claimed numbers. 

solution: abandoned problems should be deducted from claimed problems.

For example, if I claim 6 problems and then abandon 2 of them then:
claimed = 4; abandoned = 2;

**Comment by chamidu-supeshala** [comment]
@emurgobot claim

**Comment by chamidu-supeshala** [comment]
fixed #180
@emurgobot done
@emurgobot label "done"

**Comment by chamidu-supeshala** [comment]
@emurgobot label "done"

**Comment by chamidu-supeshala** [comment]
@emurgobot done
