### ISSUE TITLE
Problem: [/new] Add new problem form input order counter-intuitive

### ISSUE THREAD

**Issue by samuelralak** [EmurgoHK/Emurgis#18]
Problem: The order of input fields from the Add New Problem is counter-intuitive and confusing i.e it starts with a detailed explanation of the problem then summary. A more natural order would be: 
- Brief summary or Title
- A detailed explanation of the problem
- Optional description

A good example of such an order is the github issues. I would propose that a similar format should be followed.

ping @gazhayes @AshHimself

**Comment by gazhayes** [comment]
I know it looks strange, but the intention is to make people think through the problem first (when they write the detailed description) and then the summary should be much clearer. 

I agree that it looks weird though. The other thing we could do is have a confirmation type page displaying everything they have entered  (as say, step 2) and the summary can be added on that page.

**Comment by samuelralak** [comment]
aah I see. this makes more sense now
> I know it looks strange, but the intention is to make people think through the problem first (when they write the detailed description) and then the summary should be much clearer.

Having two steps for such a simple would  be overkill, we could either leave it as it is or have the summary as the very last input, below the option textbox. We could always get feedback from users.

**Comment by gazhayes** [comment]
Solved in #22
