### ISSUE TITLE
problem: unnecessary breadcrumb bar

### ISSUE THREAD

**Issue by gazhayes** [EmurgoHK/Emurgis#181]
problem: unnecessary breadcrumb bar

<img width="519" alt="screen shot 2018-06-05 at 11 22 04 pm" src="https://user-images.githubusercontent.com/8143945/40985728-4bec382a-6917-11e8-8a22-3deb03fe7152.png">

**Comment by samuelralak** [comment]
The breadcrumb is currently static. It needs to change depending on the current page visited

**Comment by anbud** [comment]
I agree, active class on the menu would look nicer.

**Comment by samuelralak** [comment]
away with the breadcrumb

**Comment by samuelralak** [comment]
@emurgobot claim

**Comment by samuelralak** [comment]
@emurgobot label "done"

**Comment by samuelralak** [comment]
done in #199
