### ISSUE TITLE
Problem: [/new] Nothing happens when user clicks submit

### ISSUE THREAD

**Issue by samuelralak** [EmurgoHK/Emurgis#19]
Problem: When user submits the new problem, no other action is performed informing the user that the form has been submitted/saved or failed validation which would lead the user to assume that the operation failed or simply the form does not work.

Solution: Notify the user if the operation was successful/failed on submit and possibly redirect to different page upon success. Possible pages to redirect to either problems page and problem item page.

**Comment by gazhayes** [comment]
The best thing to do here is probably just direct users to the detail page for that problem (which doesn't exist yet).

There shouldn't be any errors other than stuff that can be shown in-line, the only real thing so far is a missing compulsory field.

**Comment by samuelralak** [comment]
We should probably display validation errors as well
<img width="1257" alt="screen shot 2018-05-29 at 2 47 40 pm" src="https://user-images.githubusercontent.com/4476552/40657142-6a89fca4-634f-11e8-8a25-b77a8aeac448.png">

**Comment by gazhayes** [comment]
Yeah, use inline bootstrap errors. I think that's being used on /addcoin for blockrazor so might be able to use that for reference.

**Comment by samuelralak** [comment]
claiming this

**Comment by geekyd** [comment]
@samuelralak @gazhayes The user should be redirected when the problem is successfully created.
