### ISSUE TITLE
problem: can't tell which notifications have been visited

### ISSUE THREAD

**Issue by gazhayes** [EmurgoHK/Emurgis#191]
problem: notifications are all marked as read when opening the notification page. When users visit one of them and go back to the notification page it's not possible to see what's already been visited.

possible solution: only mark individual notifications as read onClick

**Comment by chamidu-supeshala** [comment]
@emurgobot claim

**Comment by chamidu-supeshala** [comment]
fixed #201
@emurgobot done
@emurgobot label "done"
