### ISSUE TITLE
problem: users cannot easily see their own logged problems

### ISSUE THREAD

**Issue by gazhayes** [EmurgoHK/Emurgis#192]
problem: users cannot easily see their own logged problem, the filters aren't really working for this, it's annoying to untick everything.

solution: create another view for problems that the user has created, add sidebar button

**Comment by samuelralak** [comment]
@emurgobot claim

**Comment by samuelralak** [comment]
@emurgobot label "in progress"

**Comment by samuelralak** [comment]
@emurgobot remove "in progress"

**Comment by samuelralak** [comment]
@emurgobot label "done"

**Comment by samuelralak** [comment]
done in #203
