### ISSUE TITLE
problem: users cannot log 'FYI' type problems

### ISSUE THREAD

**Issue by gazhayes** [EmurgoHK/Emurgis#195]
problem: sometimes users just need everyone to acknowledge a new piece of information rather than have someone claim and solve a problem.

solution: on the new problem page, add a checkbox "this is an FYI". If a problem is an FYI, don't allow it to be claimed. Instead, show a button "Got it", which appends the user's name to a list of people who have read and understood the problem.

**Comment by anbud** [comment]
@emurgobot claim

**Comment by anbud** [comment]
Done in #208.

@emurgobot label "done"
