### ISSUE TITLE
problem: owners cannot kick claimers

### ISSUE THREAD

**Issue by gazhayes** [EmurgoHK/Emurgis#196]
problem: sometimes it's necessary for an owner of a problem to remove the person who claimed it so that someone else can claim it, but we can't currently do this.

**Comment by samuelralak** [comment]
@emurgobot claim

**Comment by samuelralak** [comment]
@emurgobot label "in progress"

**Comment by samuelralak** [comment]
@emurgobot remove "in progress"

**Comment by samuelralak** [comment]
@emurgobot label "done"

**Comment by samuelralak** [comment]
done in #227
