### ISSUE TITLE
problem: extra line breaks included in markdown text

### ISSUE THREAD

**Issue by gazhayes** [EmurgoHK/Emurgis#202]
problem: extra line breaks included in markdown text

<img width="1136" alt="screen shot 2018-06-06 at 9 44 34 pm" src="https://user-images.githubusercontent.com/8143945/41041897-e8508c14-69d2-11e8-9deb-49314124c8f6.png">

This is the markdown for the above:
```
Possible solutions:
- Craft a really good tag line that sums up what we do
- Explicitly list out what we do (the address and contact info can go on the left hand side under the name, and a list of stuff can go on the right hand side.
- Mentioning Cardano somehow is probably also something we should do
```

**Comment by chamidu-supeshala** [comment]
@emurgobot claim
