### ISSUE TITLE
problem: incorrect validation of field lengths

### ISSUE THREAD

**Issue by gazhayes** [EmurgoHK/Emurgis#204]
problem: incorrect validation of field lengths

<img width="275" alt="screen shot 2018-06-06 at 10 18 46 pm" src="https://user-images.githubusercontent.com/8143945/41043976-bacaf0b8-69d7-11e8-9206-406aa9a39be6.png">

**Comment by chamidu-supeshala** [comment]
fixed #207
@emurgobot done
@emurgobot label "done"
