### ISSUE TITLE
problem: no solved problems graph

### ISSUE THREAD

**Issue by gazhayes** [EmurgoHK/Emurgis#205]
problem: no solved problems graph

solution: use chart.js to render a bar chart on the /stats route above the table.

The x-axis should be user's names, and y-axis (the bars) should be how many problems they have solved.

**Comment by samuelralak** [comment]
whoever will take this might consider checking out `https://coreui.io/demo/#main.html` for examples on how they could structure the UI. CoreUI uses chartjs as well.

**Comment by anbud** [comment]
@emurgobot claim

**Comment by anbud** [comment]
Done in #225.

@emurgobot label "done"
