### ISSUE TITLE
problem: no dependency indication on sub-problem

### ISSUE THREAD

**Issue by gazhayes** [EmurgoHK/Emurgis#210]
problem: no dependency indication on sub-problem

solution: 
1. add a warning bar or something to sub-problem's detail page saying "this problem is blocking x other problems from being completed"
2. Put a warning icon in-line next to the problem summary on the home route

**Comment by anbud** [comment]
@emurgobot claim

**Comment by anbud** [comment]
Done in #239.

@emurgobot label "done"
