### ISSUE TITLE
problem: problem owners can't deal with solutions that don't solve the problem

### ISSUE THREAD

**Issue by gazhayes** [EmurgoHK/Emurgis#214]
problem: problem owners can't deal with solutions that don't solve the problem

solution: when a problem is tagged as "ready for review" allow problem owners to nullify this. This should convert the highlighted "solution" into an ordinary message and tag the problem as "open". This should notify the person who originally "solved" it.

Prompt the owner to explain why this solution didn't work and put the answer somewhere.

**Comment by samuelralak** [comment]
@emurgobot claim

**Comment by samuelralak** [comment]
@emurgobot label "in progress"

**Comment by samuelralak** [comment]
@emurgobot remove "in progress"

**Comment by samuelralak** [comment]
@emurgobot label "done"

**Comment by samuelralak** [comment]
done in #244
