### ISSUE TITLE
problem: incorrect claimed stats for some users

### ISSUE THREAD

**Issue by gazhayes** [EmurgoHK/Emurgis#216]
Problem: some users are not seeing the right stats for their own items.

For example: 
This is what user Ryan King sees as his own stats:
![photo6109611410175666186](https://user-images.githubusercontent.com/8143945/41082608-79b1de9a-6a61-11e8-80d7-dc403b9ed42b.jpg)

This is what I see:
<img width="1417" alt="screen shot 2018-06-07 at 2 46 09 pm" src="https://user-images.githubusercontent.com/8143945/41082632-8e8a8bb4-6a61-11e8-872b-0d7799a94a22.png">

**Comment by anbud** [comment]
@emurgobot claim

**Comment by anbud** [comment]
I was changing some other stats related stuff in #226 and this one appears to be fixed.
Check it out, please. :)
