### ISSUE TITLE
problem: when maintainers delete a problem no record is kept

### ISSUE THREAD

**Issue by gazhayes** [EmurgoHK/Emurgis#220]
problem: when maintainers delete a problem no record is kept, and no feedback is provided to the user

Solution: prompt the maintainer for a reason why they are deleting the problem. Add this as a comment on the problem detail page but as a warning box or something very obvious.

Instead of removing the object from the collection, add a "maintainer removed" flag (or whatever) and hide it from the home route listings but **keep it in the owner's list of problems (/logged)** (this might require adding another checkbox). Also add a new sidebar button "rejected problems".

Add another statistic to the stats page: "rejected problems" for each user.

**Comment by anbud** [comment]
@emurgobot claim

**Comment by anbud** [comment]
Done in #226.

@emurgobot label "done"
