### ISSUE TITLE
problem: users aren't given enough guidance on how to log problems

### ISSUE THREAD

**Issue by gazhayes** [EmurgoHK/Emurgis#221]
problem: users aren't given enough guidance on how to log problems

solution: add a modal for each field of the new problem page.

Problem statement field:
> Carefully write the issue by describing the problem you face or observe. You SHOULD seek consensus from others on the accuracy of your observation to ensure that what you think is a problem really is actually a problem. You should also seek consensus on the value of solving the problem. 
> 
> Any non-problems will be deleted and added to your non-problem statistics.
> 

Solution statement field:
> What is the **simplest** possible solution? You SHOULD NOT log any ideas, suggestions, or any solutions to problems that are not explicitly documented above. 

Problem summary field:
> Briefly describe the issue so that others can quickly understand what it is. If you cannot add "Problem:" to the front of your statement and have it still make perfect sense then it isn't a problem statement and will be deleted.

**Comment by AshHimself** [comment]
A modal? Are you thinking a little ? icon what the click to get this information?

**Comment by gazhayes** [comment]
A modal that pops up when they start editing these fields will solve the problem. Now, it will introduce the problem of an annoying modal that pops up each time they add a problem but that can be resolved by letting them turn it off permanently and adding a help icon. It would also be good to allow maintainers to reset the flag that turns it off so that it's forced back on again for users who keep making mistakes.

**Comment by anbud** [comment]
@emurgobot claim
