### ISSUE TITLE
problem: search bar in bad position 

### ISSUE THREAD

**Issue by gazhayes** [EmurgoHK/Emurgis#232]
problem: search bar in bad position 

solution: move to the nav/menu bar.

**Comment by samuelralak** [comment]
@emurgobot claim

**Comment by samuelralak** [comment]
@emurgobot label "in progress"

**Comment by gazhayes** [comment]
@samuelralak how you going with this?

**Comment by samuelralak** [comment]
Its been a generally unproductive weekend, just getting back to the grind 😢 

@gazhayes  the search filter is 'tightly' coupled with the documents-index (problems) page. Moving its position to the header will not work, at least not without changing its current implementation or hacking it somehow. Am thinking of floating the search input to the left of the problems page. This may not follow the original solution but it will improve the page's UI.

@anbud @AshHimself if you guys might have any other ideas, I would be more than happy to hear them.

**Comment by anbud** [comment]
@samuelralak, if you want to 'hack' it, you can put the search bar in the header and access reactive-vars (filter) and everything from the documents-index template with `Blaze.getView()`. [Here's an example](https://gist.github.com/hexsprite/1c5de32266f8e77d0d1a) of how that works. That way you can easily set the filter, even though it's on a different template.

**Comment by samuelralak** [comment]
aah I see. giving that a try now

**Comment by samuelralak** [comment]
@emurgobot remove "in progress"

**Comment by samuelralak** [comment]
@emurgobot label "done"

**Comment by samuelralak** [comment]
done in #251
