### ISSUE TITLE
Problem: not sure what this blue background is for

### ISSUE THREAD

**Issue by gazhayes** [EmurgoHK/Emurgis#234]
Problem: not sure what this blue background is for and I don't really have time to work it out. Whoever knows, please let me know :)

<img width="1662" alt="screen shot 2018-06-08 at 2 34 36 pm" src="https://user-images.githubusercontent.com/8143945/41142709-331b7f68-6b29-11e8-8af8-9cb03473895f.png">

**Comment by samuelralak** [comment]
Those are problems with Emurgis itself

**Comment by gazhayes** [comment]
Thanks @samuelralak
