### ISSUE TITLE
Problem: [regression] owners cannot close problems

### ISSUE THREAD

**Issue by gazhayes** [EmurgoHK/Emurgis#236]
Problem: [regression] owners cannot close problems once solved. The "XXX XXX has solved this problem" button is gone.

**Comment by samuelralak** [comment]
@gazhayes apologies, I intentionally left that button out since the `accept solution` button would also close the the problem. But come to think of it, users would also need to close the problem without explicitly accepting a solution. I honestly failed here 🤦‍♂️

**Comment by gazhayes** [comment]
Oh wait, this is actually my fault, I just didn't see the button to accept the solution.

**Comment by gazhayes** [comment]
OK it turns out this is broken for old problems that were created before we implimented the "solution" box. We can deal with this manually so that's cool.
