### ISSUE TITLE
problem: Bad UX in menu

### ISSUE THREAD

**Issue by AshHimself** [EmurgoHK/Emurgis#238]
problem: The current menu is offering a bad UX and will not scale well. 

solution: where possible make use of current views and use drop down filters to change the data set. No need to have 3 views to see (requested, claimed, rejected etc) suggest adding a drop down filter with common options?

**Comment by gazhayes** [comment]
The separation of views (linked on sidebar) makes it a lot easier for users, think of it as just saving the right checkbox options to quickly switch between them instead of having to manually edit the view every 2 seconds.

Apart from that, yeah the checkboxes are getting cluttery.

**Comment by AshHimself** [comment]
ok let's do another ticket for checkboxes then if that's the case. Works for me.

**Comment by gazhayes** [comment]
@AshHimself can you log it?

**Comment by AshHimself** [comment]
To confirm. Raise a ticket to cleanup the filter? but leave the menu as is?

**Comment by gazhayes** [comment]
Ah, yeah keep the sidebar, it makes it nice and easy to use. But definitely clean up the filter menu(s)
