### ISSUE TITLE
Problem: some users are accidentally making Emurgis problems

### ISSUE THREAD

**Issue by gazhayes** [EmurgoHK/Emurgis#242]
Problem: Users sometimes tick the Emurgis box by accident when adding problems

Solution: Add a heading to the page when the Emurgis box is ticked "You are reporting a problem with the Emurgis platform itself", also maybe make the background of the page or form "emurgis" blue or something.

**Comment by samuelralak** [comment]
@emurgobot claim

**Comment by samuelralak** [comment]
@emurgobot label "in progress"

**Comment by samuelralak** [comment]
@emurgobot remove "in progress"

**Comment by samuelralak** [comment]
@emurgobot label "done"

**Comment by samuelralak** [comment]
done in #245
