### ISSUE TITLE
Problem: cannot upload images

### ISSUE THREAD

**Issue by gazhayes** [EmurgoHK/Emurgis#247]
Problem: cannot upload images when adding a new problem or making a comment.

solution: don't re-invent the wheel. Copy all the image uploading stuff from Blockrazor. Upload directory should be /var/www/static/images. One difference between this and blockrazor however is that we don't need to prevent the same image being uploaded multiple times.

**Comment by AshHimself** [comment]
@emurgobot claim

**Comment by AshHimself** [comment]
@gazhayes - Only different I think is possibly making this into a reusable method. We had a lot of code duplication on BR.

**Comment by AshHimself** [comment]
@emurgobot unclaim

I'm wasting time on this trying to get my upload stuff working on windows. I get my macbook back this week but until then someone else could probably do this.

**Comment by anbud** [comment]
@emurgobot claim

**Comment by anbud** [comment]
Done in #255.

@emurgobot label "done"

**Comment by Ayanrocks** [comment]
Remember to close this issue
