### ISSUE TITLE
Problem: cannot add dependency from sub-problem

### ISSUE THREAD

**Issue by gazhayes** [EmurgoHK/Emurgis#248]
Problem: currently, dependencies can only be added *as* dependencies. It's not possible to add parents to a problem.

Solution: on the problem creation/edit view, allow adding parents in the same way that dependencies are currently added. This should be phrased carefully to avoid confusion: "The following problems cannot be completed until this problem is closed" followed by "Add new".

**Comment by anbud** [comment]
@emurgobot claim

**Comment by anbud** [comment]
Done in #252.

@emurgobot label "done"
