### ISSUE TITLE
Problem: command to insert in mongo is throwing an error

### ISSUE THREAD

**Issue by Ayanrocks** [EmurgoHK/Emurgis#261]
Problem: The command to insert in mongo locally which is 
`wget https://fixme.fixme/static/dump.tar.gz && tar -xvf dump.tar.gz && mongorestore -h 127.0.0.1 --port 3001 -d meteor dump/meteor`
is throwing the following error: 
`
--2018-06-12 10:49:08--  https://fixme.fixme/static/dump.tar.gz
wget: /home/ayanrocks/.netrc:4: unknown token "method"
wget: /home/ayanrocks/.netrc:4: unknown token "interactive"
Resolving fixme.fixme (fixme.fixme)... failed: Name or service not known.
wget: unable to resolve host address ‘fixme.fixme’
`
Ubuntu 16.04 x64

**Comment by gazhayes** [comment]
This is not a mongo error it's simply a URL error because we haven't been publishing the database.

The solution is actually to remove that part from the Readme.

**Comment by Ayanrocks** [comment]
So then it needs to be removed from all the repos. Seems like the Documentation needs a lot of updating

**Comment by gazhayes** [comment]
Just remove it from emurgis, the database is not important for development, but on other repos we need to fix the database dump so that it works.

**Comment by Ayanrocks** [comment]
@emurgobot claim

**Comment by Ayanrocks** [comment]
@emurgobot  done
