### ISSUE TITLE
problem: tests are failing

### ISSUE THREAD

**Issue by gazhayes** [EmurgoHK/Emurgis#272]
problem: tests are failing

ping @anbud @AshHimself

**Comment by anbud** [comment]
I'll fix them. 

@emurgobot claim

**Comment by anbud** [comment]
Fixed in #274.

@emurgobot label "done"

**Comment by anbud** [comment]
They appear to be failing again for some reason. I'll check it out.

@emurgobot remove "done"

**Comment by anbud** [comment]
Should be fixed in #278.

@emurgobot label "done"
