### ISSUE TITLE
Problem: can't see which problems a problem is blocking

### ISSUE THREAD

**Issue by gazhayes** [EmurgoHK/Emurgis#279]
Problem: it's not possible to see exactly which problems are being blocked by a child dependency.

solution: add a list of parent issues on the currency detail page. Instead of the banner "this problem is blocking 1 other problem from being completed" add "this problem is blocking the following problems from being completed" and list them with links back to those problems.

**Comment by geekyd** [comment]
Fixed in #281 

@emurgobot label "done"

**Comment by geekyd** [comment]
@emurgobot remove "in progress"

**Comment by gazhayes** [comment]
@geekyd I think something might have broken with your last PR, I no longer see anything on a dependency to indicate that it's blocking anything.

**Comment by geekyd** [comment]
@gazhayes I'm sorry about the confusion, fixing it.

**Comment by geekyd** [comment]
Fixed in #283 

@emurgobot label "done"
