### ISSUE TITLE
Problem: developers cannot login without an emurgo.io account

### ISSUE THREAD

**Issue by samuelralak** [EmurgoHK/Emurgis#28]
Problem: @emurgio.io accounts are currently required to login; logging in using an email with a different domain will fail. We need to allow developers who do not have an @emurg.io account access the software as well.

**Comment by samuelralak** [comment]
@gazhayes I may be wrong but this may involve maintaining a list of known developers somewhere in the backend. We cannot just grant access to anyone claiming to be a developer

**Comment by gazhayes** [comment]
Let's just use demo accounts that we can share with developers we already trust. That one I sent you is one and the other is devtest2

This way we can have a moderator and user demo account.

**Comment by gazhayes** [comment]
Though we can probably allow unverified email sign up too if some env var is true (DEV=true) or whatever. I'm not sure how that works on Windows though.

**Comment by samuelralak** [comment]
We could check `process.env.NODE_ENV` - if its set to `development`, we can allow unverified emails to login/signup
> Though we can probably allow unverified email sign up too if some env var is true (DEV=true) or whatever. I'm not sure how that works on Windows though.

**Comment by gazhayes** [comment]
There we go, that will work.

**Comment by samuelralak** [comment]
cool. working on it

**Comment by samuelralak** [comment]
fixed in [#34](https://github.com/EmurgoHK/Emurgis/pull/34)
