### ISSUE TITLE
problem: no user profile page to see other user's details

### ISSUE THREAD

**Issue by gazhayes** [EmurgoHK/Emurgis#280]
problem: there's currently no detailed view of users

solution: add a basic user profile view where other users can see details about that user.
- A list of problems they have solved
- A list of problems they have logged
- Their recent activity (comments, logged problems, claimed problems, solved problems, closed problems)

**Comment by geekyd** [comment]
@emurgobot claim

**Comment by geekyd** [comment]
Fixed in #284 

@emurgobot label "done"

**Comment by geekyd** [comment]
@emurgobot remove "in progress"
