### ISSUE TITLE
problem: layout isn't very good on small screens

### ISSUE THREAD

**Issue by gazhayes** [EmurgoHK/Emurgis#288]
problem: layout isn't very good on small screens. Emurgis needs to work *really* well on phones since a lot of people catch up with this stuff on the train or whatever on the way to work.

The things that are important are viewing problems, commenting, adding problems, etc. Things like the stats page aren't important for mobile.

**Comment by AshHimself** [comment]
@emurgobot claim

**Comment by AshHimself** [comment]
@gazhayes - first pass is done. I honestly think viewing problems as cards on a mobile device will offer a better UX and remove the need for scrolling horizontally (this is the approach most apps take, checkout the Jira mobile app. Amazing UX)

**Comment by gazhayes** [comment]
Yeah I agree, you can do it that way if you want ;)

But keep it as a table for larger screens

**Comment by AshHimself** [comment]
Problem indexs are now displayed as cards instead of of tables and offers a better ux IMO. I suggest closing this ticket and ill raise more tickets from other responsive issues I have found (not created :) ) #315

**Comment by AshHimself** [comment]
@gazhayes - anything left on this mate? or you ok to close?
