### ISSUE TITLE
Problem: [/documentEdit] Problems not editable

### ISSUE THREAD

**Issue by samuelralak** [EmurgoHK/Emurgis#30]
Problem: Clicking on the edit button on  a problem redirects to an empty page

Solution: redirect users to an edit form when the edit button is clicked. disallow other users other than the owner to edit the problem.

**Comment by samuelralak** [comment]
Claiming this

**Comment by samuelralak** [comment]
done in [#40](https://github.com/EmurgoHK/Emurgis/pull/40)

**Comment by AshHimself** [comment]
@samuelralak I think you deleted my new claimProblem method unintentionally. Can you fix this, just went crazy wondering where it went as I swore I did it last night :)

**Comment by samuelralak** [comment]
oh man, am very sorry about that chief. they must have been deleted when I
did a git rebase. fixing that immediately. am very sorry mate.

**Comment by samuelralak** [comment]
@AshHimself when merged, please confirm whether [#48](https://github.com/EmurgoHK/Emurgis/pull/48) fixes whats missing. Went through [#35](https://github.com/EmurgoHK/Emurgis/pull/35) and [#41](https://github.com/EmurgoHK/Emurgis/pull/41) line by line. Found
