### ISSUE TITLE
Problem: same color of status badge as background for dependent problems

### ISSUE THREAD

**Issue by geekyd** [EmurgoHK/Emurgis#301]
Problem: same color of status badge as background for dependent problems

Solution: Change the color of the badge
![screen shot 2018-06-19 at 12 43 21 pm](https://user-images.githubusercontent.com/12807846/41582146-68993728-73be-11e8-802c-acafca7e380c.png)

**Comment by gazhayes** [comment]
Actually a nicer solution (the grey rows don't look very good) is to remove the specific colouring of the table rows and instead add a stop sign icon (or whatever), similar to how we show dependencies.

**Comment by gazhayes** [comment]
This icon in red will do nicely: https://fontawesome.com/icons/ban?style=solid

**Comment by samuelralak** [comment]
@emurgobot claim

**Comment by samuelralak** [comment]
@emurgobot remove "in progress"
@emurgobot label "done"

**Comment by samuelralak** [comment]
done in #314
