### ISSUE TITLE
problem: not clear what time estimates are

### ISSUE THREAD

**Issue by gazhayes** [EmurgoHK/Emurgis#304]
problem: it's not clear what time estimates are for.

solution:

<img width="440" alt="screen shot 2018-06-19 at 3 45 06 pm" src="https://user-images.githubusercontent.com/8143945/41583771-0d34cdba-73d8-11e8-80b1-325cf0500847.png">
Change to "Estimated workload: xx minutes"   
<hr />
<img width="175" alt="screen shot 2018-06-19 at 3 50 22 pm" src="https://user-images.githubusercontent.com/8143945/41583934-83ac6eda-73d8-11e8-877d-e863e6432c81.png">
Change to "Estimate workload (in minutes)"   
<hr />

<img width="465" alt="screen shot 2018-06-19 at 3 51 42 pm" src="https://user-images.githubusercontent.com/8143945/41584017-b7e27474-73d8-11e8-9704-02f4a3aba735.png">

Change to:
How many minutes do you think you need to spend working on this problem?

and change the placeholder to:
Enter the estimated workload (in minutes)
<hr />

**Comment by samuelralak** [comment]
@emurgobot claim

**Comment by samuelralak** [comment]
@emurgobot remove "in progress"
@emurgobot label "done"

**Comment by samuelralak** [comment]
done in #313
