### ISSUE TITLE
problem: double text on new problem page

### ISSUE THREAD

**Issue by gazhayes** [EmurgoHK/Emurgis#306]
problem: 
<img width="1574" alt="screen shot 2018-06-19 at 4 06 02 pm" src="https://user-images.githubusercontent.com/8143945/41584776-bb5a4684-73da-11e8-9fc4-2c18cc0fa302.png">

**Comment by samuelralak** [comment]
@emurgobot claim

**Comment by samuelralak** [comment]
@emurgobot remove "in progress"
@emurgobot label "done"

**Comment by samuelralak** [comment]
done in #309
