### ISSUE TITLE
Problem: links on user profile page do not go back to the actual issue

### ISSUE THREAD

**Issue by gazhayes** [EmurgoHK/Emurgis#308]
Problem: links on items on user profile page do not go back to the actual issue

**Comment by samuelralak** [comment]
@emurgobot claim

**Comment by samuelralak** [comment]
@emurgobot remove "in progress"
@emurgobot label "done"

**Comment by samuelralak** [comment]
done in #316

**Comment by gazhayes** [comment]
Cool new profile pic @samuelralak ;)

**Comment by samuelralak** [comment]
thank you @gazhayes  😄
