### ISSUE TITLE
Problem: user's date of birth not tracked

### ISSUE THREAD

**Issue by gazhayes** [EmurgoHK/Emurgis#312]
Problem: user's date of birth not tracked

Solution: add user date of birth (store in epoch/unix time).

Add a modal launched automatically after the home route has loaded. Ask for user's date. If already exists, don't launch the modal.

Text for modal: Please enter your date of birth. This will be used as part of the account recovery process if anything goes wrong.

**Comment by AshHimself** [comment]
Fixed in #322
@emurgobot label "done"
@emurgobot done

**Comment by Ayanrocks** [comment]
Please close the issue
