### ISSUE TITLE
problem: subscription have to keep reloading

### ISSUE THREAD

**Issue by gazhayes** [EmurgoHK/Emurgis#318]
problem: subscription have to keep reloading. This is especially annoying on mobile. For example when users go to the problem detail page and then back to the home route, the subscriptions reload again from scratch.

solution: i'm pretty sure subscache will fix this.

**Comment by anbud** [comment]
Yap, SubCache should help.

@emurgobot claim

**Comment by anbud** [comment]
Done in #321.

@emurgobot label "done"
@emurgobot remove "in progress"
