### ISSUE TITLE
problem: tests are broken

### ISSUE THREAD

**Issue by gazhayes** [EmurgoHK/Emurgis#319]

**Comment by anbud** [comment]
Shall be fixed.

@emurgobot claim

**Comment by gazhayes** [comment]
<img width="409" alt="screen shot 2018-06-16 at 11 16 21 am" src="https://user-images.githubusercontent.com/8143945/41611480-8f1a8960-7422-11e8-99ff-c3750e140374.png">

**Comment by anbud** [comment]
Done in #320.

@emurgobot label "done"
@emurgobot remove "in progress"
