### ISSUE TITLE
problem: value of user's time is not apparent

### ISSUE THREAD

**Issue by gazhayes** [EmurgoHK/Emurgis#324]
problem: users are asked to provide a time estimate when claiming a problem. However there's nothing to remind them of how valuable their time actually is, which means they might do things inefficiently.

Solution:
Inform the user of how many of these tasks they can do before they become useless:

estimated productive time remaining (minutes) = (current age - 65) * 48 * 5 * 6 * 60 * 0.7

[number of minutes remaining before age 65 which are productive, not on holiday, not in pain, not sick]

Number of tasks = estimated productive minutes remaining / workload for this task (minutes)

When the user enters the workload estimate when claiming a problem, display (onKeyUp or whatever) how many tasks like this they can do:

"{{first name}}, you have approximately x productive hours remaining in your life. This means you can only solve x problems like this. Every minute counts.

**Comment by anbud** [comment]
I love this one. :D 

@emurgobot claim

**Comment by anbud** [comment]
Done in #325.

@emurgobot label "done"
@emurgobot remove "in progress"
