### ISSUE TITLE
Problem: users cannot add dependencies

### ISSUE THREAD

**Issue by gazhayes** [EmurgoHK/Emurgis#33]
Problem: users can't create nested issues (cannot add dependencies).

The solution to this should allow unlimited levels of nesting (by having dependencies on issues that have dependencies). It should also prevent circular dependencies because this will cause problems in the UI later when viewing as some kind of tree showing all issues.

**Comment by geekyd** [comment]
Claiming this

**Comment by geekyd** [comment]
@emurgobot claim

**Comment by geekyd** [comment]
@gazhayes @AshHimself @samuelralak @anbud 

Adding a relationship table to maintain the dependencies of the problems. Whenever a new dependency is added traverse through the dependencies of the problem to check for a cycle. 

Is there a better solution for this ?

**Comment by gazhayes** [comment]
Hmmmm, this is a difficult one to solve. The only simpler solution I can think of is to use functional style language instead of imperative but I don't think anyone (here) other than myself can do this and I don't have the time.

**Comment by geekyd** [comment]
@gazhayes Should I label it for later or should I implement it using what I suggested?

**Comment by gazhayes** [comment]
You can do the way you want ;)

**Comment by gazhayes** [comment]
How are you going with this?

**Comment by geekyd** [comment]
I will be sending a PR for this soon

**Comment by gazhayes** [comment]
@geekyd friendly ping ;)

How are you going with this?

**Comment by geekyd** [comment]
@gazhayes Apologies for the delay. I was a bit caught up. I have added basic functionality. Will add the logic for circular dependency in the next PR. If possible please suggest some solution that does not include exhaustive search.

**Comment by geekyd** [comment]
fixed #209 
@emurgobot done
@emurgobot label "done"
