### ISSUE TITLE
Problem: can't login to emurgis.org:8000

### ISSUE THREAD

**Issue by samuelralak** [EmurgoHK/Emurgis#331]
Problem: I currently cannot login into the dev test account. Getting the below error which definitely has something to with the Google oAuth setup
<img width="649" alt="screen shot 2018-06-26 at 11 30 00 am" src="https://user-images.githubusercontent.com/4476552/41899199-8712ca40-7934-11e8-8ae8-8705faf9f05d.png">

ping @gazhayes

**Comment by gazhayes** [comment]
Weird, I didn't change anything

**Comment by samuelralak** [comment]
I suspect this block of code [here](https://github.com/EmurgoHK/Emurgis/blob/master/imports/startup/server/accounts.js). It runs on start up
```
ServiceConfiguration.configurations.insert({
  service: 'google',
  clientId: Meteor.settings.google ? Meteor.settings.google.clientId : '',
  secret: Meteor.settings.google ? Meteor.settings.google.secret : ''
})
```

**Comment by Ayanrocks** [comment]
I think u didnt passed the client_id. How you setted up the oauth?

**Comment by gazhayes** [comment]
Oauth is configured directly in the database. So yes that code block is probably the problem. Production should only ever look at the database.

**Comment by samuelralak** [comment]
since google OAuth is no longer needed in development, I would suggest deleting that section into oblivion.  We might as well add the login buttons provided by the accounts package inside the login modal in development.
