### ISSUE TITLE
Problem: [problem detail page] wrong icon in claim confirmation popup

### ISSUE THREAD

**Issue by akatrodiya** [EmurgoHK/Emurgis#338]
Problem: In Problem detail page, success icon in claim confirmation popup while in all other confirmation popups (In same page or other pages as well) icon is warning.

Solution: Replace success icon with warning icon in Claim popup.

**Comment by anbud** [comment]
@emurgobot claim

**Comment by anbud** [comment]
Done in #342.

@emurgobot label "done"
@emurgobot remove "in progress"
