### ISSUE TITLE
problem: no API to fetch issues 

### ISSUE THREAD

**Issue by gsovereignty** [EmurgoHK/Emurgis#343]
problem: there's no API to fetch issues and state, so we cannot solve https://github.com/EmurgoHK/Emurgolance/issues/54

**Comment by samuelralak** [comment]
@emurgobot claim

**Comment by samuelralak** [comment]
installed and using `restivus` package for this purpose; it seemed to be the most recently updated package - last commit was 1 year ago - compared to the packages I have seen and also easy to use. 

I haven't authenticated the endpoints yet, I will create another ticket for that. The default auth may not work well with Google Auth - we will have to override that with a custom auth. Restivus briefy explains how to do this in their docs.

**Comment by samuelralak** [comment]
@emurgobot remove "in progress"
@emurgobot label "done"

**Comment by samuelralak** [comment]
done in #345

**Comment by anbud** [comment]
We should probably implement some sort of oauth for API authentification, it seems easy.

There are meteor packages that do this already, it's just a matter of generating tokens.

**Comment by gazhayes** [comment]
@anbud 100% agreed
