### ISSUE TITLE
Problem: don't understand what roles there are

### ISSUE THREAD

**Issue by akatrodiya** [EmurgoHK/Emurgis#356]
problem: don't understand what roles there are

**Comment by anbud** [comment]
Currently, there are two roles, regular users and moderators. Moderators just have the `moderator` flag set to true in the user object. :)

**Comment by akatrodiya** [comment]
got it. But current we need to go into database and set this flag, shouldn't we have something from UI?

**Comment by anbud** [comment]
@gazhayes said that it's a sufficient solution for now. We should probably implement some sort of a moderator/admin panel later on with those functionalities.

**Comment by gazhayes** [comment]
For now it's ok. I'll add an issue when this becomes a problem (when I want to add more maintainers).
