### ISSUE TITLE
Problem : AUTHORS file link is broken

### ISSUE THREAD

**Issue by MadanBhandari** [EmurgoHK/Emurgis#358]
Problem : AUTHORS file link is broken in Readme

Solution : Fix the link by correcting file name/path.

**Comment by MadanBhandari** [comment]
Sorry, I forgot to claim before start. Fixed in #359 

@emurgobot label "done"

**Comment by Ayanrocks** [comment]
Please also add your name in the AUTHORS file and close this issue.
