### ISSUE TITLE
Problem: unable to unclaim an issue

### ISSUE THREAD

**Issue by AshHimself** [EmurgoHK/Emurgis#36]
Solution: Add functionality to unclaim an issue once claimed.

**Comment by AshHimself** [comment]
Claim

**Comment by AshHimself** [comment]
Fixed in #50

**Comment by AshHimself** [comment]
@gazhayes - Are we expecting to have a dev environment setup for Emurgis so we can ensure all our changes are working in production as well?

**Comment by gazhayes** [comment]
Yep, I'll deploy a production server over the next few days
