### ISSUE TITLE
Problem: edit & delete buttons overflow the parent on problems page

### ISSUE THREAD

**Issue by geekyd** [EmurgoHK/Emurgis#379]
Problem: edit & delete buttons overflow the parent on problems page in case of mobile screens(small screens)
![screen shot 2018-07-12 at 8 11 09 pm](https://user-images.githubusercontent.com/12807846/42640474-00d6c556-8610-11e8-87b8-ca3b1026c05a.png)

Solution: properly align the buttons on problems page in case of small screens

**Comment by akatrodiya** [comment]
Done in #413 

@emurgobot label "done"
@emurgobot remove "in progress"
