### ISSUE TITLE
Problem: content overflowing on notifications page for small screens

### ISSUE THREAD

**Issue by geekyd** [EmurgoHK/Emurgis#380]
Problem: content overflowing on notifications page for small screens

![screen shot 2018-07-12 at 8 13 54 pm](https://user-images.githubusercontent.com/12807846/42640675-716f1c6e-8610-11e8-9144-802b027ec4bc.png)
Solution: apply responsive design to the page

**Comment by akatrodiya** [comment]
@emurgobot claim

**Comment by akatrodiya** [comment]
Done in #415 

@emurgobot label "done"
@emurgobot remove "in progress"
