### ISSUE TITLE
Problem: content overflowing on mentions page in small screens

### ISSUE THREAD

**Issue by geekyd** [EmurgoHK/Emurgis#381]
Problem: content overflowing on mentions page in small screens
![screen shot 2018-07-12 at 8 13 43 pm](https://user-images.githubusercontent.com/12807846/42640784-ada97936-8610-11e8-90c5-f85e1cd4c78b.png)

Solution: implement responsive design to the page

**Comment by akatrodiya** [comment]
@emurgobot claim

**Comment by akatrodiya** [comment]
Done in #421

@emurgobot label "done"
@emurgobot remove "in progress"
