### ISSUE TITLE
Problem: Normalise users name when creating a problem

### ISSUE THREAD

**Issue by AshHimself** [EmurgoHK/Emurgis#39]
Solution: Capture the the users name in problem table when raising a problem thus allowing mongoDB queries. 

@anbud - This the best way to do it as apposed to creating a helper and looking up the users table every single time.

**Comment by anbud** [comment]
@AshHimself, both approaches have good and bad sides.

Doing it like you've described uses a little bit more storage and doesn't react to username changes, but it is more optimal performance-wise as it's not querying the database every time. 

Saving only user's `_id` and querying the username after needs a subscription and uses a little bit more resources, but it does react to username changes.

So, I agree, there's nothing wrong with normalizing user's username when creating a new problem.

**Comment by anbud** [comment]
Since user `_id`s are already saved when submitting a problem, I'm guessing that the issue here is that owner's username is not shown on the problem page, and the solution is just writing a helper that fetches the username.

**Comment by anbud** [comment]
@AshHimself, is this one same as #90 then?

**Comment by AshHimself** [comment]
Closing per advise from @gazhayes, this isn't a problem and we should just create a helper to query the users ID.
