### ISSUE TITLE
Problem: [Common] All content with table view are overlaying

### ISSUE THREAD

**Issue by akatrodiya** [EmurgoHK/Emurgis#391]
Problem: [Common] content with table view in all pages are overlaying

Solution: Decide common responsive view for table contents and set it in all pages where contents are displaying in table view

**Comment by MadanBhandari** [comment]
This issue still exist ?

**Comment by MadanBhandari** [comment]
I'll look into this.

@emergobot claim

**Comment by MadanBhandari** [comment]
@emurgobot claim

**Comment by MadanBhandari** [comment]
Related Issue #390 and fixed in #426 

I'll looking into remaining table.

**Comment by MadanBhandari** [comment]
Done in #449 

@emurgobot done

**Comment by MadanBhandari** [comment]
@gazhayes I can't close this issue, this is fixed, please check and close.
