### ISSUE TITLE
problem: cannot quote people

### ISSUE THREAD

**Issue by gazhayes** [EmurgoHK/Emurgis#393]
Problem: when quoting people (in comments) the formatting doesn't signify that it's a quote.

solution: perhaps somehow use the '>' mark to delineate quotations and format this differently when rendering the comment.

**Comment by anbud** [comment]
@emurgobot claim

**Comment by anbud** [comment]
Done in #394.

@emurgobot label "done"
@emurgobot remove "in progress"
