### ISSUE TITLE
Problem: [Home page] 'New Problem' Flow is not correct when user is not logged in

### ISSUE THREAD

**Issue by akatrodiya** [EmurgoHK/Emurgis#399]
Problem: click on 'New Problem' button it redirect to sign in

Solution: Open sign in popup, if user not signed in and try to add new problem

**Comment by anbud** [comment]
@emurgobot claim

**Comment by anbud** [comment]
Done in #404.

@emurgobot label "done"
@emurgobot remove "in progress"
