### ISSUE TITLE
Problem: [Profile page] Exception in template helper 'getSummaryById'

### ISSUE THREAD

**Issue by akatrodiya** [EmurgoHK/Emurgis#400]
Problem: Exception in template helper 'getSummaryById' and it logs in browser console

Solution: Add proper return value for helper with condition that problem is getting or not

**Comment by anbud** [comment]
@emurgobot claim

**Comment by anbud** [comment]
Done in #405.

@emurgobot label "done"
@emurgobot remove "in progress"

**Comment by gazhayes** [comment]
@akatrodiya can you verify this is fixed and close if so :)
