### ISSUE TITLE
problem: problems that are ready for review are marked as stale

### ISSUE THREAD

**Issue by gazhayes** [EmurgoHK/Emurgis#406]
problem: problems that are ready for review are marked as stale.

solution: if a problem is ready for review, never mark it as stale.

**Comment by gazhayes** [comment]
ping @anbud

**Comment by gazhayes** [comment]
This appears to also be affecting closed problems.

**Comment by geekyd** [comment]
@emurgobot claim

**Comment by geekyd** [comment]
Done in #407 

@emurgobot label "done"
@emurgobot remove "in progress"
