### ISSUE TITLE
problem: rejected problems being marked as stale

### ISSUE THREAD

**Issue by gazhayes** [EmurgoHK/Emurgis#409]
problem: rejected problems being marked as stale

solution:  there may be other statuses now or in the future which should not be marked as stale. At present, all statuses are marked as stale except for those specifically listed. This should be flipped around, no statuses should be marked as stale unless they are "in progress" or "open".

**Comment by anbud** [comment]
Done in #410.

@emurgobot label "done"
@emurgobot remove "in progress"
