### ISSUE TITLE
Problem: UI is not updated after login

### ISSUE THREAD

**Issue by gazhayes** [EmurgoHK/Emurgis#43]
Problem: when logging in with Google, the UI still asks users to sign in, both on the login page and also in the nav bar.

This is probably deeper than a UI issue because I've discovered a whole lot of other issues that could be related to a user not really being signed in, or possibly a broken google-login package.

**Comment by samuelralak** [comment]
[#52](https://github.com/EmurgoHK/Emurgis/pull/52) should fix this
