### ISSUE TITLE
Problem: [Side menu] Online user section overlap menu items

### ISSUE THREAD

**Issue by akatrodiya** [EmurgoHK/Emurgis#431]
Problem: [Side menu] Online user section overlap menu items, so if more users are online then it cover all height and it is not scrollable.

Solution: Set max height for online user section, and scroll that section is more users are online

**Comment by akatrodiya** [comment]
@emurgobot claim

**Comment by akatrodiya** [comment]
Done in #433 

@emurgobot label "done"
@emurgobot remove "in progress"

**Comment by gazhayes** [comment]
@emurgobot claim
