### ISSUE TITLE
problem: image upload directory has changed

### ISSUE THREAD

**Issue by gazhayes** [EmurgoHK/Emurgis#439]
problem: the image upload director has changed from this: 
/home/gareth/static/static/images/emurgis/
accessible via emurgis.org/images/emurgis/

to this: 
/home/gareth/emurgis_assets/static/images/
accesible via emurgis.org/images/

Code and tests need to be updated.

**Comment by anbud** [comment]
@emurgobot claim

**Comment by anbud** [comment]
Done in #442.

@emurgobot done
