### ISSUE TITLE
Problem : Multiple usernames are not useful

### ISSUE THREAD

**Issue by MadanBhandari** [EmurgoHK/Emurgis#445]
Problem : Multiple usernames are not useful

Solution : 
Keep only one and unique username for every user.

_**Question** : Is there any specific requirement for multiple usernames or use case ?_

ping : @gazhayes

**Comment by anbud** [comment]
I believe they're used as nicknames for the mentioning system, I'm not sure if they should be removed.

**Comment by gazhayes** [comment]
Yeah they are for mentions, so we need them
