### ISSUE TITLE
problem: some dependencies have security issues

### ISSUE THREAD

**Issue by gazhayes** [EmurgoHK/Emurgis#447]
problem: some dependencies have security issues
<img width="749" alt="screen shot 2018-09-20 at 6 11 44 pm" src="https://user-images.githubusercontent.com/8143945/45811825-be96be80-bd00-11e8-82dc-fd1d930fe15c.png">

**Comment by samuelralak** [comment]
@emurgobot claim

**Comment by samuelralak** [comment]
@emurgobot done

don in #448
