### ISSUE TITLE
Problem: login and signup fields exist

### ISSUE THREAD

**Issue by gazhayes** [EmurgoHK/Emurgis#45]
Problem: the UI suggests to users that its possible to log in or create an account without using Google sign in when this is not actually the case.

Solution: remove all log in and sign up UI elements, the only one that should remain is log in with Google.

**Comment by anbud** [comment]
Claim.

**Comment by samuelralak** [comment]
Andrej this is already fixed. Havent made a PR yet

**Comment by anbud** [comment]
Heh, ok, I'm leaving it for you then. :)
