### ISSUE TITLE
Problem: new issues are deleted from mongo on page refresh

### ISSUE THREAD

**Issue by gazhayes** [EmurgoHK/Emurgis#47]
Problem: 
1. Add a new problem. 
2. Go to the home route.
3. Problem exists.
4. Refresh page.
5. Problem no longer exists and is removed from the collection.

I haven't checked if this is just being saved to a local collection and cleared on refresh, or if there's some weird bug actually deleting it. It could also be related to the weird login bug in #43

**Comment by geekyd** [comment]
@gazhayes Same for me, unable to reproduce it.

**Comment by gazhayes** [comment]
Ok must be local for me

**Comment by anbud** [comment]
Yap, this works locally for me as well.
