### ISSUE TITLE
Problem: Nothing happens when delete button is clicked

### ISSUE THREAD

**Issue by geekyd** [EmurgoHK/Emurgis#51]
Problem: Nothing happens when delete button is clicked

Solution: Implement deletion of problem on `/` route

**Comment by geekyd** [comment]
Claiming this :)

**Comment by geekyd** [comment]
@gazhayes Are we going to use hard delete or soft delete in the application? If we are going to use soft delete what field should we have to check the state?

**Comment by gazhayes** [comment]
Hard delete. Let's walk on the wild side.

**Comment by geekyd** [comment]
Done in #57
