### ISSUE TITLE
Problem: not enough tests

### ISSUE THREAD

**Issue by gazhayes** [EmurgoHK/Emurgis#55]
Problem: pull requests generally aren't being submitted with tests.

Solution: all pull requests should include tests to ensure the problem they solve doesn't become a problem again later (e.g. if new code breaks it). Client side is not important because users will notice straight away but server side should be tested.

Ping @anbud @samuelralak @ashhimself

**Comment by anbud** [comment]
Agreed, it'll be a lot easier to keep track of errors if tests are written from the beginning.

**Comment by geekyd** [comment]
Agreed
