### ISSUE TITLE
problem: solution field is not displayed

### ISSUE THREAD

**Issue by gazhayes** [EmurgoHK/Emurgis#60]
Problem: text added to the solution field is not displayed on the problem detail page.

Solution: add solution field to collection if not already there and add view logic

**Comment by samuelralak** [comment]
@gazhayes the solution field is already present for new problems. just a mtter of adding it to the details page

**Comment by samuelralak** [comment]
claim

**Comment by samuelralak** [comment]
@emurgobot claim

**Comment by samuelralak** [comment]
@emurgobot label "done"

**Comment by samuelralak** [comment]
fixed in [#71](https://github.com/EmurgoHK/Emurgis/pull/71)

**Comment by samuelralak** [comment]
I know why 🤦‍♂️ . The changes were overwritten while doing a git rebase. Will submit another PR for this.

**Comment by samuelralak** [comment]
@emurgobot claim

**Comment by samuelralak** [comment]
@emurgobot label "in progress"

**Comment by samuelralak** [comment]
fixed in [#77](https://github.com/EmurgoHK/Emurgis/pull/77)

**Comment by samuelralak** [comment]
@emurgobot remove "in progress"

**Comment by samuelralak** [comment]
@emurgobot label "done"
