### ISSUE TITLE
problem: no status tag for problems

### ISSUE THREAD

**Issue by gazhayes** [EmurgoHK/Emurgis#64]
Problem: there's no status tag to indicate the current status of problems.

When a problem is claimed, it should automatically be given the "In progress" status.
When a user resolves an issue, it should be tagged as "ready for review" so that the creator of the project can then either "close" the issue or mark it as "open" again. Once closed, the issue should simply be tagged as "closed" and the UI logic can then be used to hide it from view.

**Comment by samuelralak** [comment]
We would need the following abilities 
- [ ] ability to mark problem as resolved
- [ ] ability to open/close a problem
The above can be done in two seperate issues.

* when a problem is created it should have a status of `open` by default

**Comment by samuelralak** [comment]
@emurgobot claim

**Comment by samuelralak** [comment]
@emurgobot label "in progress"

**Comment by samuelralak** [comment]
@gazhayes all dependencies have been merged for this issue.

**Comment by samuelralak** [comment]
@emurgobot remove "in progress"
