### ISSUE TITLE
Problem: Users cannot mark problem as resolved

### ISSUE THREAD

**Issue by samuelralak** [EmurgoHK/Emurgis#72]
Problem: Users have no way to mark the problem as resolved once they have claimed it.

**Comment by samuelralak** [comment]
@blockrazorbot claim

**Comment by samuelralak** [comment]
@emurgobot claim

**Comment by samuelralak** [comment]
@emurgobot claim

**Comment by gazhayes** [comment]
Only allow the user who claimed it to mark it as resolved

**Comment by samuelralak** [comment]
@emurgobot remove "in progress"

**Comment by samuelralak** [comment]
@emurgobot label "done"

**Comment by samuelralak** [comment]
done in [#75](https://github.com/EmurgoHK/Emurgis/pull/75)
