### ISSUE TITLE
Problem: no clean admin theme

### ISSUE THREAD

**Issue by gazhayes** [EmurgoHK/Emurgis#76]
Here are some potential solutions:

https://github.com/pratikborsadiya/vali-admin
https://github.com/akveo/ngx-admin
https://coreui.io
https://www.npmjs.com/package/gentelella
https://startbootstrap.com/template-overviews/sb-admin/

@AshHimself @anbud @samuelralak @geekyd please vote :)

**Comment by AshHimself** [comment]
Looking now, when reviewing, if you can have a quick review of the source code (if available) and access how complex at may be to integrate in.

**Comment by AshHimself** [comment]
coreUI looks good and looks pretty light on including packages we would NEVER use.

**Comment by samuelralak** [comment]
Voting for [sb-admin](https://startbootstrap.com/template-overviews/sb-admin/) for the following very 
 reasons:
- clean minimalist design IMHO
- less bloated
- light [2 MBs] - not as light as coreUI though
- full package - no pro version required
- easily customisable
- I generally like it

**Comment by anbud** [comment]
I'm voting for CoreUI, love the way it looks, and it seems light enough.

**Comment by geekyd** [comment]
CoreUI looks good to me. Clean design & lighter than others.

**Comment by gazhayes** [comment]
CoreUI it is!
