### ISSUE TITLE
Problem: Uncaught TypeError: addProblem.call is not a function at Object.submit

### ISSUE THREAD

**Issue by gazhayes** [EmurgoHK/Emurgis#8]
Problem: on [/new] I'm getting Uncaught TypeError: addProblem.call is not a function.

addProblem is a ValidatedMethod and is defined in /imports/api/documents/both/problemMethods.js

**Comment by AshHimself** [comment]
@gazhayes are you expecting this to all work? As the way the code is now it won't insert any problem unless I do above and beyond the original issue :)

**Comment by samuelralak** [comment]
@AshHimself am getting the below error in my console

**Comment by AshHimself** [comment]
?? Not pushed anything yet. The power to my house has just gone out :/

**Comment by samuelralak** [comment]
@AshHimself sorry about that chief. I have updated my initial comment as well.

**Comment by AshHimself** [comment]
Yep its all been fixed. Will push when I have power :D

**Comment by AshHimself** [comment]
@gazhayes Fixed in #13

Created another issue for related issues I found whilst resolving that also need resolving.
