### ISSUE TITLE
problem: no live checking for field lengths

### ISSUE THREAD

**Issue by gazhayes** [EmurgoHK/Emurgis#83]
Problem: fields are not currently checked for length when the user types. This is annoying, especially on the problem summary field.

Solution: check length onKeyUp (or whatever) and display remaining characters.

Fields should have the following maximums:
problem field: 500 chars
solution field: 500 chars
problem summary: 62 chars (will be prepended with 'problem:' which is 8 chars.

**Comment by samuelralak** [comment]
@emurgobot claim
