### ISSUE TITLE
problem: CoreUI not used

### ISSUE THREAD

**Issue by gazhayes** [EmurgoHK/Emurgis#87]
Problem: CoreUI is not used.

Solution: implement coreUI (https://coreui.io).

@samuelralak I think you'll like this one, if not, @geekyd might want to have a look.

**Comment by samuelralak** [comment]
sweet. taking a look. @emurgobot claim

**Comment by samuelralak** [comment]
@gazhayes should we change the overall layout of Emurgis (give it the CoreUI admin look with side panel) or leave it as it is and decide later?

I have already integrated the CoreUi styles and components

**Comment by gazhayes** [comment]
Looking good! I guess send a PR with this first and then do the rest as a separate problem.

**Comment by geekyd** [comment]
Looks nice. Great work @samuelralak

**Comment by samuelralak** [comment]
sweet. thanks. sending PR in a bit

**Comment by samuelralak** [comment]
done in [#111](https://github.com/EmurgoHK/Emurgis/pull/111)

**Comment by samuelralak** [comment]
@emurgobot label "done"
