### ISSUE TITLE
Problem: no user statistics

### ISSUE THREAD

**Issue by gazhayes** [EmurgoHK/Emurgis#91]
Problem: there's currently no way to track the performance of each user.

Solution: give problem creators two options when closing an issue: "this is no longer a problem" and "xxxx has solved this problem" with xxxx being the user who claimed the issue.

Track how many problems each user has logged, and how many they have claimed *and* the owner has declared they have actually solved.

ping @anbud

**Comment by anbud** [comment]
@emurgobot claim

**Comment by anbud** [comment]
Done in #98.

@emurgobot label "done"
@emurgobot remove "in progress"
