### ISSUE TITLE
problem: problems not marked as "in progress" once claimed

### ISSUE THREAD

**Issue by gazhayes** [EmurgoHK/Emurgis#92]
problem: problems not marked as "in progress" once claimed, still marked as "open" on home route and "claimed" but also "open" on detail page.

**Comment by samuelralak** [comment]
I could swear this was working well before

**Comment by gazhayes** [comment]
I thought it was too.

**Comment by samuelralak** [comment]
hmm. We may have to find or decide on a way  to avoid regression

**Comment by geekyd** [comment]
My bad, I accidentally deleted the changes by @samuelralak in #81 while experimenting with the idea of a common method. Fixing it.

@emurgobot claim

**Comment by geekyd** [comment]
done in #96 

@emurgobot label 'done'

**Comment by geekyd** [comment]
@emurgobot label "done"
