### ISSUE TITLE
problem: users do not get notifications

### ISSUE THREAD

**Issue by gazhayes** [EmurgoHK/Emurgis#94]
problem: users do not get notifications when someone replies to a problem they have logged or a problem they have commented on.

solution: implement a basic notification system. The simplest way is probably to have some problem level "watch" flag  or whatever that is set to true when a user creates a problem, comments on a problem, or watches a problem. Then a notification method (or whatever) can be triggered whenever an event occurs.

**Comment by anbud** [comment]
@emurgobot claim

**Comment by anbud** [comment]
Done in #116.

@emurgobot label "done"
